### PR TITLE
Sqlx migrations

### PR DESCRIPTION
**Pull request by mendelt**
Added a .env.example file. A .env file can be useful to set up environment variables and this file is automatically picked up by sqlx-cli so it can find the database
Moved the sql in the schema directory to the migrations directory where sqlx expects them.
Fixed a typo in the sql
Some documentation on how to install and run migrations using the slqx command line tool was added

Sqlx also has a migrate! macro to run migrations from code. Not sure if thats what we want but I can add that later.

### CODE REVIEW

**Comment by jbr** [comment]
Haha the "typo" was because I was using sqlite. I'd prefer sqlite personally, but I'm not sure how much work it would be to adjust this PR for that

**Comment by mendelt** [comment]
Ah, completely missed that :-) I just assumed mysql and it worked. But sqlite makes sense for an example project. Way easier to set up. Maybe then we can just use a hardcoded $DATABASE_URL to a database-file in the folder the example is run from? That would make setting things up even easier.

I don't think it will be too hard to change. Not sure if I can configure sqlx-cli to connect to a sqlite database though. But I was going to look at using the migrate! macro directly from the code anyway. I'll try the command-line approach first and report back...

**Comment by mendelt** [comment]
I fixed things for use with sqlite. sqlx cli runs fine from the command-line as described in the README.md. Of course this only works as long as you're using a database-file and not an in-memory database.
I can also look into running migrations from code. Not sure where to add that though. Should they run every time on startup? Sqlx keeps track of which migrations have run in the database so that should not cause any problems

**Comment by jbr** [comment]
I've thought a bit about this and although I'm excited for sqlx-cli, I don't think an example repo should use a beta release. When there's a release that can be installed with `cargo install sqlx-cli`, I'll definitely reopen this

**Comment by mendelt** [comment]
np, I'll give a heads up here if I see any movement on the sqlx-cli side. It's pretty quiet over there at the moment.

**Pull request closed without merging**
